### ISSUE TITLE
afterAll doesn't work with Jasmine 2.0.0

### ISSUE THREAD

**Issue by georgemillo** [testdouble/jasmine-before-all#3]
Every time I call afterAll, no matter where from, I get the following error:

```
TypeError: Cannot read property 'id' of undefined
    at root.afterAll (/path/to/jasmine-before-all.js:27:46)
    at Suite.<anonymous> (/path/to/MySpec.js:63:5)
    at Env.describe (path/to/jasmine-2.0.0/jasmine.js:613:25)
    at jasmineInterface.describe (path/to/jasmine-2.0.0/boot.js:37:18)
    at Suite.<anonymous> (/path/to/CloudSpec.js:47:3)
    at Env.describe (/path/to/jasmine-2.0.0/jasmine.js:613:25)
    at jasmineInterface.describe (/path/to/jasmine-2.0.0/boot.js:37:18)
    at /path/to/CloudSpec.js:27:1
```

beforeAll works fine.

Could these be an incompatibility issue with Jasmine 2.0.0? i haven't testing with older versions.

**Comment by anupoju84** [comment]
Is this fixed now?

**Comment by searls** [comment]
Unfortunately, this won't be possible with this library. Sorry to have kept it open in case you were holding out hope!
